#!/bin/bash

#echo 'depricated'
#exit
username=$1

if [ "${username}" == "" ]
then
	echo "./build_client <username>"
	exit
fi

cd /etc/openvpn/easy-rsa/ 
source vars
./build-key ${username}
#cp /etc/openvpn/ccd/template /etc/openvpn/ccd/${username}
